#@IgnoreInspection BashAddShebang

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load in !!! LOCAL ZSHRC !!!
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# This makes it easier to see which terminal you are using in jupyter lab
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  tmux,
  docker
)

source $HOME/.zshrc-local

### Set PATH
# The following HOME directories should be correctly
# defined in the local zshrc file (which is sourced above)
export PATH=$ANACONDA_BIN${PATH:+:${PATH}}
export PATH=$MATLAB_BIN${PATH:+:${PATH}}
export PATH=$USER_BIN${PATH:+:${PATH}}
export PATH=$SCRIPTS_HOME${PATH:+:${PATH}}
export PATH=$CUDA_BIN${PATH:+:${PATH}}

export LD_LIBRARY_PATH=$CUDA_LIB64_HOME${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export LD_LIBRARY_PATH=$CUDA_CUPTI_LIB64_HOME${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

################################################
### Common aliases across all configurations ###
################################################

### GENERAL ###
alias clc='clear'
alias add='git add --all;git status'
alias gh='cd ~/GitHub'
alias gl='cd ~/GitLab'
alias doctoc='doctoc --github --title "**Table of Contents** generated with [DocToc](https://github.com/thlorenz/doctoc) $(echo "\n\nLast Update: `date +%Y-%m-%d`")"'

### PYTHON ###
alias sa='conda activate'
alias sd='conda deactivate'

# Jupyter general
alias jn='start_jupyter.sh --notebook'
alias jl='start_jupyter.sh'

# Jupyter server for specific projects
alias jl_hottbox='start_jupyter.sh --port=8000'

# Tunneling to jupyter servers
alias jl_eeik='start_jupyter.sh --connect=ee-ik1614lx --remote-port=7777 --port=7777'
alias jl_docik='start_jupyter.sh --connect=doc-ik1614 --remote-port=7778 --port=7778'

### MATLAB ###
alias mat='matlab -nodisplay -nosplash'

### Latex ###
# Consider using make_pdf.sh custom script for generating pdf
alias pdflatex='pdflatex -output-directory=build'



source $ZSH/oh-my-zsh.sh
