# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load in !!! LOCAL ZSHRC !!!
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $HOME/.zshrc-local
source $ZSH/oh-my-zsh.sh

# User configuration
# source $ZSH_CUSTOM


alias clc='clear'
alias add='git add --all;git status'
alias grep='grep --color=auto'


############### CD TO SPECIFIC DIRECTORIES ###############
alias gh='cd ~/GitHub'
alias gl='cd ~/GitLab'

############### REMOTE CONTROL ###############
# ssh to my EEE machine
alias eee='ssh eee_ubuntu'
# ssh to my EEE_MAC_mini machine
alias eeem='ssh eee_mac_mini'


### JupyterLab
alias jl='source deactivate;source activate py36;jupyter lab'
# jupyter notebook with Dropbox as home
alias jld='cd ~/Dropbox/1_ILIA/;source deactivate;source activate py36;jupyter lab'


############### PYTHON ###############
# alias python="python3"
alias anaco='anaconda-navigator'
alias sa='source activate'
alias sd='source deactivate'



alias show='defaults write com.apple.finder AppleShowAllFiles YES;killall Finder /System/Library/CoreServices/Finder.app'
alias hide='defaults write com.apple.finder AppleShowAllFiles NO;killall Finder /System/Library/CoreServices/Finder.app'
