#!/usr/bin/env bash

#####################################################
### Specific configurations for the local machine ###
###     This file is sourced by the ~/.zshrc      ###
#####################################################

ZSH_THEME="agnoster"
ZSH_CUSTOM=__CONFIG_HOME__/dotfiles/zsh/custom
SCRIPTS_HOME=__CONFIG_HOME__/scripts

## Uncomment and correctly define these if you are going to be
## this software (they are sourced by the main ~/.zshrc)
#ANACONDA_HOME=/path/to/anaconda/bin
#MATLAB_HOME=/path/to/matlab/bin
#CUDA_HOME=/usr/local/cuda/bin
#CUDA_LIB64_HOME=/usr/local/cuda/lib64
#CUDA_CUPTI_LIB64_HOME=/usr/local/cuda/extras/CUPTI/lib64


#######################################
#########       ALIASES       #########
#######################################

### REMOTE CONTROL ###


### MOUNT DEVICES ###
